### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by 6aTaPeI9** [thedeaddan/pyqt5_contribution#1]
Привет! ДН попросил глянуть код, в целом не плохо, основные замечания по стилю кода.
1) Нет комментариев, трудно читать код человеку который видит его впервые. Т.к проект пока что не слишком большой, отсутствие комментариев не вызывает проблем, но в будущем сам начнешь забывать что делает та или иная функция)
Надо добавить комменты к:

- Модулю. В самом верху модуля
`"""" Этот модуль делает содержит такую то логику
"""`
- К классам.
- К методам классов

2) Если твой модуль является точкой старта программы, то удобно в самом низу добавлять следующее условие, чтобы избежать ситуации когда твой модуль импортируется в прикладном коде и это инициирует запуск приложения.
https://github.com/thedeaddan/pyqt5_contribution/blob/f39cc81b5a6169bdf41dcad806747caec3f6a9c6/main.py#L139-L142
```
if __name__ == '__main__:
  app = QtWidgets.QApplication([])
  w1 = First()
  w1.show()
  sys.exit(app.exec())
```

3) Переменные обьявленные в области видимости модуля являются глобальными, дополнительно писать global не нужно. Ну и я бы не стал обьявлять изменяемые переменные в глобальной области видимости, Внеси их лучше в поля класса Second. При переходе в третье окно я бы передал эти значения в конструктор класса Third.
https://github.com/thedeaddan/pyqt5_contribution/blob/f39cc81b5a6169bdf41dcad806747caec3f6a9c6/main.py#L7

4) Названия ui контроллов, push_button/lineedit/horizontalSlider и т.д, если ты делаешь приложение в редакторе PyQt ты можешь быстро посмотреть что за что отвечает, но маловероятно что человек который будет оценивать твой код полезет в редактор. Так что куда удобней когда эти обьекты называются так, чтобы по их названию можно было понять что они делают из за что отвечают.

5) По пепу8 принято ставить пробелы между любыми операторами +/-/%/* и т.д, а так же после запятых. Можешь почитать правила оформления кода тут:
https://github.com/thedeaddan/pyqt5_contribution/blob/f39cc81b5a6169bdf41dcad806747caec3f6a9c6/main.py#L111
https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html

6) Не плохо, но вот так симпатичней .
https://github.com/thedeaddan/pyqt5_contribution/blob/f39cc81b5a6169bdf41dcad806747caec3f6a9c6/main.py#L56-L61
```
if stable == 0:
    return QMessageBox.critical(self, "Ой..", "Вы не заполнили все данные!", QMessageBox.Ok)

self.w3 = Third()
self.w3.show()            
```

7) Сильное дублирование кода в функциях changeValueLine/changeValueLine_2/changeValueLine_3/changeValue/changeValue_2/changeValue_3. Можно все сделать через одну, что сильно сократит кол-во кода.
```
from functools import partial
    def __init__(self):
        super(Second, self).__init__()
        self.ui = second_window.Ui_MainWindow_2()
        self.ui.setupUi(self)

        self.deposite_args = {
            'first': 0,
            'second': 0,
            'third': 0
        }
        first_change = partial(self.changeValue, 'first')
        second_change = partial(self.changeValue, 'second')
        third_change = partial(self.changeValue, 'second')

        self.ui.lineEdit.textChanged.connect(first_change)
        self.ui.lineEdit_2.textChanged.connect(second_change)
        self.ui.lineEdit_3.textChanged.connect(third_change)

        self.ui.horizontalSlider.valueChanged[int].connect(partial(first_change, edit_line=self.ui.lineEdit))
        self.ui.horizontalSlider_2.valueChanged[int].connect(partial(second_change, edit_line=self.ui.lineEdit_2))
        self.ui.horizontalSlider_2.valueChanged[int].connect(partial(third_change, edit_line=self.ui.lineEdit_3))

        self.ui.pushButton.clicked.connect(self.open_third)


    def changeValue(self, depos_arg_key: str, value: str, edit_line: QtWidgets.QLineEdit = None):
        """
            Изменение значение
        """
        if not str(value).isdigit:
            edit_line.setText('0')

        self.deposite_args[depos_arg_key] = int(value)

        if edit_line:
            edit_line.setText(str(value))

        return self.change_output()
```
Если разрешишь публичный push, закину в репу рабочую ветку чтобы ты мог потыкаться.
Остальное по мелочи. Если будут вопросы пиши в телегу @be3kor

**Comment by thedeaddan** [comment]
Приветик. Спасибо за оценку кода и проделанную работу. По пунктам проходиться не буду, скажу в общем. Я был ограничен во времени(чем дольше - тем ниже оценка) и работал с интерфейсом PyQT5 второй раз. Мне была поставлена задача сделать как можно раньше, я сделал все по ТЗ, но он все равно влепил мне трояк хоть и до этого поставил 5 ;) 
Твои предложения учту, но работа с этим проектом закончена и даже не хочется возвращаться к нему из-за таких приколов с переобуванием с оценкой. Ещё раз спасибо)
